# Generated by Django 2.0.2 on 2018-12-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('localidad', models.CharField(max_length=200)),
                ('tipo', models.PositiveSmallIntegerField()),
                ('cobro', models.PositiveSmallIntegerField()),
                ('entradas', models.PositiveSmallIntegerField()),
                ('salidas', models.PositiveSmallIntegerField()),
                ('ingreso_actual', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
