# Generated by Django 2.0.2 on 2018-12-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Sucursal')),
                ('localidad', models.CharField(max_length=200, verbose_name='Localidad')),
                ('tipo', models.PositiveSmallIntegerField(verbose_name='Tipo')),
                ('cobro', models.PositiveSmallIntegerField(verbose_name='Esquema')),
                ('entradas', models.PositiveSmallIntegerField(verbose_name='Entradas')),
                ('salidas', models.PositiveSmallIntegerField(verbose_name='Salidas')),
                ('ingreso_actual', models.PositiveIntegerField(verbose_name='Ingresos')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de ultima modificacion')),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
                'ordering': ['-created'],
            },
        ),
    ]
