# Generated by Django 2.0.2 on 2018-12-25 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('N', 'Nocturno')], max_length=1, verbose_name='Turno')),
                ('boletaje', models.PositiveSmallIntegerField(verbose_name='Boletos Expedidos')),
                ('recuperados', models.PositiveIntegerField(verbose_name='Recuperados')),
                ('caja', models.PositiveSmallIntegerField(verbose_name='Caja')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de corte')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de ultima modificacion')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Encargado')),
            ],
            options={
                'verbose_name': 'Corte',
                'verbose_name_plural': 'Cortes',
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='cobro',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='ingreso_actual',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='tipo',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(default=5512345678, max_length=200, verbose_name='Telefono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='localidad',
            field=models.CharField(max_length=200, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='corte',
            name='sucursal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.Sucursal', verbose_name='Sucursal'),
        ),
    ]
