# Generated by Django 2.0.2 on 2019-02-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripcion', '0003_suscripcion_apellidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='apellidos',
            field=models.CharField(default='-', max_length=200, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre(s)'),
        ),
    ]
