# Generated by Django 2.0.2 on 2019-01-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_auto_20181226_0338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'ordering': ['nombre'], 'verbose_name': 'sucursal', 'verbose_name_plural': 'sucursales'},
        ),
        migrations.AddField(
            model_name='corte',
            name='detalles',
            field=models.TextField(default=0, verbose_name='Detalles'),
            preserve_default=False,
        ),
    ]
