# Generated by Django 2.0.2 on 2019-02-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_sucursal_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='corte',
            name='cortesias',
            field=models.PositiveIntegerField(blank='True', default=0, verbose_name='Cortesias'),
        ),
        migrations.AddField(
            model_name='corte',
            name='incompletos',
            field=models.PositiveIntegerField(blank='True', default=0, verbose_name='Incompletos'),
        ),
        migrations.AddField(
            model_name='corte',
            name='noSellados',
            field=models.PositiveIntegerField(blank='True', default=0, verbose_name='No sellados'),
        ),
        migrations.AddField(
            model_name='corte',
            name='propina',
            field=models.PositiveIntegerField(blank='True', default=0, verbose_name='Propina'),
        ),
        migrations.AddField(
            model_name='corte',
            name='sellados',
            field=models.PositiveIntegerField(blank='True', default=0, verbose_name='Sellados'),
        ),
        migrations.AddField(
            model_name='corte',
            name='sinPropina',
            field=models.PositiveIntegerField(blank='True', default=0, verbose_name='Sin propina'),
        ),
        migrations.AlterField(
            model_name='corte',
            name='locatarios',
            field=models.PositiveIntegerField(blank='True', default=0, verbose_name='Locales'),
        ),
        migrations.AlterField(
            model_name='corte',
            name='tolerancias',
            field=models.PositiveIntegerField(blank='True', default=0, verbose_name='Tolerancias'),
        ),
    ]
