# Generated by Django 2.0.2 on 2019-02-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_auto_20190217_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='tipo',
            field=models.CharField(choices=[('Automatizado', 'Automatizado'), ('Semi-automatizado', 'Semi-automatizado'), ('Aportacion', 'Aportacion')], default='Automatizado', max_length=200, verbose_name='Tipo'),
        ),
    ]
